general.import = [
# "./tokyo-night.toml",
    "./everforest_color.toml"
]
[cursor]

# Set to false to disable completely
smooth_motion = true
# 0.0 = cursor is not moving, 1.0 = cursor moves instantly
smooth_motion_factor = 0.5
# 0.0 = broken, 1.0 = cursor shape is unaffected by movement
smooth_motion_spring = 0.5
# Limits how the cursor size may change
smooth_motion_max_stretch_x = 3.0
smooth_motion_max_stretch_y = 1.5
# Override "block" cursor if you don't like how it looks in this fork
# block_replace_shape = "underline"

[colors.selection]
background = "0x9a0000"
text = "0x1a1b66"


[colors.cursor]
text = "0xff0000"
cursor = "0xff0000"

[font]
size = 20.0

[font.bold]
family = "MonoLisa"
style = "Bold"

[font.italic]
family = "MonoLisa Cursive"

[font.normal]
family = "MonoLisa"
style = "Regular"

[mouse]
hide_when_typing = false

[window]
opacity = 1
blur = true
decorations = "Buttonless"

[window.padding]
x = 0
y = 0

