general.import = ["./edge_color.toml"]

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[colors.cursor]
cursor = "0xc0caf5"
text = "0x1a1b26"


[colors.selection]
background = "0x33467c"
text = "0xc0caf5"

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 21.0

[font.bold]
family = "Operator-caskabold"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[font.italic]
family = "Operator-caska"
style = "Book Italic"

[font.normal]
family = "Operator-caska"
style = "Regular"

[mouse]
hide_when_typing = false

[window]
blur =true 
opacity =0.9
decorations = "ButtonLess"

[window.padding]
x = 0
y = 0


[keyboard]
