# general.import = ["./ayu_mirage.toml"]
general.import = ["./edge_aura.toml"]

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[colors.cursor]
cursor = "0xc0caf5"
text = "0x1a1b26"


[colors.selection]
background = "0x33467c"
text = "0xc0caf5"

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 22.0

[font.bold]
family = "Cascadia Code NF"
style = "Bold"

[font.offset]
x = 0
y = 8

[font.italic]
family = "Cascadia Code NF"
style = "SemiLight Italic"

[font.normal]
family = "Cascadia Code NF"
style = "Regular"

[mouse]
hide_when_typing = false

[window]
blur = true
opacity =0.9
decorations = "ButtonLess"

[window.padding]
x = 25
y = 15
