unbind C-b
unbind C-s
set -g prefix C-a
bind C-a send-prefix
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1

# set -g status off

# Move between panes using Vim-style keys with the tmux prefix key
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# open to current directory
bind u split-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# customisation begin here
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"
# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'AleckAstan/tmux-zap'
# set -g @plugin 'AleckAstan/tmux-powerkit'
set -g @plugin 'hiroppy/tmux-agent-sidebar'
set -g @plugin 'vaaleyard/tmux-dotbar'
set -g @tmux-dotbar-position top
set -g @tmux-dotbar-rounded true
set -g @tmux-dotbar-bg "default"
# set -g @plugin 'catppuccin/tmux#v2.1.0'

# set -g status-right-length 100
# set -g status-left-length 100
# set -g status-left ""
# set -g status-right "#{E:@catppuccin_status_application}"
# set -ag status-right "#[fg=#{@thm_crust},bg=#{@thm_teal}] #Antsa "
# set -ag status-right "#{E:@catppuccin_status_uptime}"
# set -ag status-right "#{E:@catppuccin_status_session}"
# set -g @catppuccin_window_default_text "#{b:pane_current_path}"
# set -g @catppuccin_window_current_text "#{b:pane_current_path}"
# set -g @catppuccin_window_default_text "#W"
# set -g @catppuccin_window_current_text "#W"
# set -g @catppuccin_window_text "#W"
# set -g @catppuccin_flavor 'mocha'
# set -g @catppuccin_window_status_style "rounded"

# tmux zap
set -g @zap_key 's'
set -g @zap_width '50%'
set -g @zap_height '40%'
set -g @zap_mode 'window' # -- session or window / default window

set -g @continuum-save-interval '15'
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'

# set -g focus-events on
# set -g status-style bg=default
set -g status-position top


# set -g @powerkit_theme "catppuccin"
# set -g @powerkit_plugins "datetime,battery,cpu,git"
# set -g @powerkit_theme_variant "latte"
# set -g @powerkit_transparent "true"
# set -g @powerkit_separator_style "normal"
# set -g @powerkit_edge_separator_style "rounded"
# set -g @powerkit_status_order "session,plugins" 
# set -g status-left-length 0
# set -g status-style "fg=$fg,bg=$bg"
# set -g status-justify right
#
# set -g status-right "#[fg=${white}, bg=${red},bold] #S #[fg=${white},nobold]"
#
# set -g status-right-length 100
# set -g status-right ""


# set-hook -g pane-focus-in "run-shell 'sketchybar --trigger tmux_update'"
# set-hook -g after-select-pane "run-shell 'sketchybar --trigger tmux_update'"
# set-hook -g after-select-window "run-shell 'sketchybar --trigger tmux_update'"
# set-hook -g client-session-changed "run-shell 'sketchybar --trigger tmux_update'"


# set -g window-status-separator "| "
# setw -g window-status-format "#W#[fg=${red1}]#{?window_zoomed_flag, 󰋱,} "
# setw -g window-status-current-format "#[fg=${red},bold]#[fg=${default},bg=${red},bold]#W#[fg=${red1}]#{?window_zoomed_flag, 󰋱,} "

# Active les bordures sur chaque vitre
# set -g pane-border-status bottom

# Crée un format de bordure qui simule un cadre
# On ajoute des espaces pour donner une impression de largeur
# set -g pane-border-format " #[fg=default]── #P: #W ── "

# Donne de l'épaisseur à la ligne
# set -g pane-border-style fg=colour238
# set -g pane-active-border-style fg=brightblue
#
# set -g pane-border-lines heavy


# bootstrap tpm
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
