#!/bin/bash
source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=10 # All paddings use this value (icon, label, background)

# Unload the macOS on screen indicator overlay for volume change
# launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar

bar=(
    height=40
    notch_display_height=40
    color=$TOKYO_NIGHT_BG
    shadow=off
    position=top
    sticky=on
    # y_offset=5
    # margin=10
    topmost=window
    padding_left=$PADDINGS
    padding_right=$PADDINGS
    blur_radius=80
    padding_left=10
    padding_right=10
)


# Setting up default values
defaults=(
    padding_left=10
    padding_right=10
    updates=when_shown
    icon.font="$FONT:Bold:13.0"
    icon.color=$ICON_COLOR
    # icon.padding_left=$PADDINGS
    # icon.padding_right=$PADDINGS
    label.font="$FONT:Semibold:13.0"
    label.color=$LABEL_COLOR
    label.padding_left=3
    label.padding_right=3
    background.height=30
    background.corner_radius=8
    background.border_width=2
    popup.background.border_width=2
    popup.background.corner_radius=9
    popup.background.border_color=$POPUP_BORDER_COLOR
    popup.background.color=$POPUP_BACKGROUND_COLOR
    popup.background.shadow.drawing=on
)

sketchybar  --bar "${bar[@]}" --default "${defaults[@]}"

# Left
# sketchybar --add item apple.logo left                                                      \
#               --set apple.logo icon=􀣺                                                         \
#                                icon.font="SF Pro:Black:16.0"                                  \
#                                label.drawing=off                 
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/yabai.sh"
# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/calendarfr.sh"

sketchybar --add item whoami right
sketchybar --set whoami label="Antsa Judicaël"

source "$ITEM_DIR/system.sh"

# source "$ITEM_DIR/ram.sh" 
# sketchybar --add alias "Control Center,Battery" right 
# sketchybar --add alias "Control Center,WiFi" right 
#
#
#
BRACKET_STYLE=(
  background.height=30
  background.color=$TOKYO_NIGHT_BG_DARK
  background.corner_radius=10
  # background.border_width=1
  # background.border_color=$TOKYO_NIGHT_BORDER
  blur_radius=20
)



sketchybar --add bracket spaces  '/space\..*/' \
           --set         spaces 

sketchybar --add bracket f_app  front_app  \
           --set         f_app "${BRACKET_STYLE[@]}" 

sketchybar --add bracket system cpu mem \
           --set system "${BRACKET_STYLE[@]}"

sketchybar --add bracket calendar_menu calendar calendarfr\
           --set calendar_menu "${BRACKET_STYLE[@]}"

sketchybar --add bracket whoami_menu whoami \
           --set whoami_menu "${BRACKET_STYLE[@]}"


# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
