#!/bin/bash

options=(
	width=8.0
	hidpi=on
    # active_color='0x80FFFFFF'
    # inactive_color='0x20FFFFFF'
    active_color='glow(0xff3b82f6)'
  inactive_color=0x40FFFFFF
	background_color=0x80FFFFFF
)

borders "${options[@]}"
